### ISSUE TITLE
Wrong indent after paren

### ISSUE THREAD

**Issue by Eiryyy** [MaxMEllon/vim-jsx-pretty#1]
I typed `return (<CR>`, but I think it's wrong indentation.
<img width="325" alt="2016-07-15 15 30 24" src="https://cloud.githubusercontent.com/assets/2590137/16865625/15cd7524-4aa1-11e6-83dd-01b65bd9c648.png">

I use these plugins (only loaded).
```
- webapi-vim: OK
- vim-jsx-pretty: OK
- lightline.vim: OK
- vim-slime: OK
- molokai: OK
- yajs: OK
- neocomplete.vim: OK
- neosnippet: OK
- vim-over: OK
- vimproc: OK
- vim-fugitive: OK
- javascript-libraries-syntax.vim: OK
- emmet-vim: OK
- vim-surround: OK
- syntastic: OK
- vimshell: OK
- vim-nodejs-complete: OK
- neosnippet-snippets: OK
- unite.vim: OK
- tagbar: OK
- es.next.syntax.vim: OK
- open-browser.vim: OK
- VimClojure: OK
- ag.vim: OK
```

**Comment by MaxMEllon** [comment]
Thank you reporting. I am japanese, so You may use japanese.

Sorry for my poor english.  so in japanese.

本プラグインはインデントの設定を含めていません．
なので，別途インデントの設定ファイルをvim のランタイムに含めることで期待したインデンテーションが可能になると思います．

次のコマンドを実行すれば，期待した動作になると思います．

```
$ mkdir -p ~/.vim/after/indent
$ cd ~/.vim/after/indent
$ wget https://gist.github.com/MaxMEllon/4f6e255cbf8c649a9750463b4e9fe414
```

**Comment by Eiryyy** [comment]
ありがとうございます。今後プラグインにインデント設定を含める予定はありますか？

**Comment by MaxMEllon** [comment]
> 。今後プラグインにインデント設定を含める予定はありますか？

あります。が、しかしユーザーによって、FileType javascriptのときにセットされている　indentexpr が異なってしまっているので、そこをどううまく吸収するかを悩んでおります。

解決案としては、

- 特定のjavascriptのインデントの設定が含まれたプラグインを依存プラグインにしつつ、jsx部分のインデントの設定を自分で書く

- 自分でjavascript部分もjsx部分もインデントの設定を書く

- jsx部分のインデントだけ別プラグインにする

が今のところ上がっております。

**Comment by MaxMEllon** [comment]
インデントの設定を実装しました [d6d1eae](https://github.com/MaxMEllon/vim-jsx-pretty/commit/d6d1eae089ff1b6d8adbf15dba3c66cf0a688ed6)

![](https://raw.githubusercontent.com/MaxMEllon/demos/master/vim-jsx-pretty/auto-indent.gif)
