### ISSUE TITLE
Broken syntax in multiline arrow function argument

### ISSUE THREAD

**Issue by lazopm** [MaxMEllon/vim-jsx-pretty#10]
I noticed this:
Just `pangloss/vim-javascript`
![vim-jasvascript](https://cloud.githubusercontent.com/assets/5622067/22073407/421ebd94-dd73-11e6-9b24-fc8e3b8646e1.png)
With `vim-jsx-pretty`
![vim-jsx-pretty](https://cloud.githubusercontent.com/assets/5622067/22073409/4415fd10-dd73-11e6-82fe-556af0f250cb.png)

**Comment by MaxMEllon** [comment]
It does not understand the reason this issue, so I fixed  simple way.

![2017-01-19 4 19 45](https://cloud.githubusercontent.com/assets/9594376/22079386/fecb019c-ddfe-11e6-92d6-90a2b906ac3e.png)

**Comment by lazopm** [comment]
@MaxMEllon thank you!
