### ISSUE TITLE
[Question] Changing tag color and matching tag highlight

### ISSUE THREAD

**Issue by HeeJoong** [MaxMEllon/vim-jsx-pretty#101]
Hi. thank you for this great plugin
with the vim-jsx-pretty default setting, the tag < and > appears to have the same color as comment syntax, as we can see No.1 and No.2 on the image below.

so I was wondering
1. if there is any way to change the color like No.3 (gray color)
2. if you know any vim plugin that can implement a matching tag highlight function on jsx file like the effect No.4

![2019-11-09_15-41](https://user-images.githubusercontent.com/16550609/68524226-8d63be00-0307-11ea-8d12-4c04b18f314f.png)

I know that I should be able to handle this kind of small issues but I'm kind of a newbie in this area. It would be really helpful if you could give me some advice on how to handle those issues.
Thank you in advance!

**Comment by yuezk** [comment]
This a good feature. And I think it can be implemented with the `searchpair()` API.

May I know which plugin do you use to highlight the right one?

**Comment by HeeJoong** [comment]
Thanks. I will try that out! The first one would be easy to implement. Do you think if there will be any chance you guys could add the pair highlighting feature in the future update?

I use 'codedark' colorscheme -> [tomasiser/vim-code-dark](https://github.com/tomasiser/vim-code-dark)
and the plugin I used for the right one is 'matchtagalways' -> [Valloric/MatchTagAlways](https://github.com/Valloric/MatchTagAlways)

**Comment by yuezk** [comment]
I will try to integrate with the MatchTagAlways plugin first, I will try to implement this feature if it doesn't work.

**Comment by yuezk** [comment]
@HeeJoong For the second question, please add the following config in your vimrc.

```
let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'javascript': 1, " <-- or 'javascript.jsx': 1
    \}
```

Please pay attention to the performance of moving cursor.

Reference: https://github.com/Valloric/MatchTagAlways/issues/30

**Comment by yuezk** [comment]
And for the first question, please try to add `hi link jsxCloseString htmlTag` into your vimrc.

**Comment by HeeJoong** [comment]
Thank you so much yuezk! That's very kind of you.
Everything working perfectly as I wanted.
I don't know how I missed adding javascript on mta_filetypes. I tried just 'js' and 'jsx' and thought maybe it's not working for the javascript file. shame on me.
Thanks and happy coding! :-)

**Comment by yuezk** [comment]
@HeeJoong Because you need to add filetypes, `js` and `jsx` are extensions, not filetypes.

**Comment by dagolinuxoid** [comment]
Btw I used `javascriptreact` (got from :set ft? command) filetype in my .vimrc config and it seems like it works properly.
