### ISSUE TITLE
Auto-indenting of properties?

### ISSUE THREAD

**Issue by vjsingh** [MaxMEllon/vim-jsx-pretty#110]
Given the following code block:
```
<Component a={1} b={2} c={3}
/>
```
or
```
<Component
  a={1} b={2} c={3}
/>
```

I can't get the plugin to auto-indent to the below. Is this supposed to work?

```
<Component
  a={1}
  b={2}
  c={3}
/>
```

**Comment by yuezk** [comment]
@vjsingh This scenario is not supported. Because the `indentexpr` in vim can only return the indent space of the current line, it can not modify the content.

See `h:indentexpr` for more info.

**Comment by vjsingh** [comment]
@yuezk OK my fault, thanks for the info.
