### ISSUE TITLE
Matching Curly Braces Highlight Wrong for JSX

### ISSUE THREAD

**Issue by maharjanaman** [MaxMEllon/vim-jsx-pretty#111]
Seems curly braces highlight, highlights different opening or closing brackets.
<img width="497" alt="Screen Shot 2019-12-10 at 14 51 21" src="https://user-images.githubusercontent.com/14164484/70514952-97721a00-1b5c-11ea-82d4-1ea720cf6d81.png">

**Comment by yuezk** [comment]
It seems not an issue of this plugin. Could you please only enable this plugin and see if it is still reproducible?

**Comment by maharjanaman** [comment]
Yes, I did that too. I was using `sheerun/vim-polyglot`, disabled it, added this one but still no luck. Other I've is just `tpope/vim-surround` and some themes. Sorry for the trouble.

**Comment by yuezk** [comment]
I can reproduce it.

I suggest you use the [itchyny/vim-parenmatch](https://github.com/itchyny/vim-parenmatch) plugin and disable the built-in matchparen plugin by adding `let g:loaded_matchparen = 1` in your vimrc. Because the former works well.

**Comment by maharjanaman** [comment]
I'm sorry, you can or can't. FYI, I'm using neovim.

**Comment by yuezk** [comment]
Yes, I can reproduce this issue on my local environment.

But I think this issue is more like an issue of the built-in matchparen plugin as it works well with itchyny/vim-parenmatch.

So, I suggest you to switch to the itchyny/vim-parenmatch plugin and disable the built-in matchparen plugin.

**Comment by yuezk** [comment]
The root cause is that the syntax group jsxEscapeJS is conflict with the built-in matchparen plugin, another solution is updating the syntax group to another name.

And if you don’t want to install another plugin, please wait the updating. I will do that soon.

**Comment by maharjanaman** [comment]
Oh ok, thanks for the effort.

**Comment by yuezk** [comment]
@maharjanaman Fixed in the latest commit.
