### ISSUE TITLE
Comments inside JSX blocks

### ISSUE THREAD

**Issue by rnmp** [MaxMEllon/vim-jsx-pretty#113]
Hey first of all, your plugin is absolutely great. Love it.

The only problem I've been having is comments inside JS blocks don't seem to be highlighted properly.

![image](https://user-images.githubusercontent.com/22627/71067187-1a3d3b00-2142-11ea-9b66-5f221bce9c3f.png)

The first comment shows the default behavior, essentially comments are not highlighted properly and reserved words such as `this` get highlighted.

The second comment illustrates what happens if i use an apostrophe, though essentially is the same issue as the previous one, JS being used to highlight instead of treating it as a comment.

The third comment is interesting because it seems to take whatever is after the `?` and somehow the next comment `what happened here?` _actually_ gets highlighed properly? it's pretty bizarre.

Anyway, if someone has already posted this pls feel free to close and point me to the right direction.

**Comment by yuezk** [comment]
@rnmp Which syntax highlighting plugin do you use for JavaScript?

**Comment by yuezk** [comment]
@rnmp I failed to reproduce this issue, below is my screenshot.
![image](https://user-images.githubusercontent.com/3297602/71172546-7c5d8380-229b-11ea-920e-1a6e02374179.png)
So, I think it's a problem of your syntax highlighting plugin you used for JavaScript.

BTW, I'm using [yuezk/vim-js](https://github.com/yuezk/vim-js) to highlight JavaScript.

**Comment by yuezk** [comment]
Noticed that you have a dotfiles repo, so I used the vimrc in that repo and didn't reproduce this problem either.

![image](https://user-images.githubusercontent.com/3297602/71173068-c72bcb00-229c-11ea-9621-0ac31d79ee7b.png)

If this issue still happens on your machine, could you provide the vimrc file to me for reproducing?

**Comment by rnmp** [comment]
Hey @yuezk thanks so much for thoroughly debug this! I did a bit more due diligence and turns out that the problem is when the filetype is `typescript.tsx`. Can you confirm you can reproduce the error when you change set that filetype?

**Comment by rnmp** [comment]
Alright, I figured it out, the problem is `HerringtonDarkholme/yats.vim`, I tried with `leafgarland/typescript-vim` and it works fine. Any reason you recommend yats over the latter? `typescript-vim` seems to work better in other scenarios too…

Anyway, feel free to close.

**Comment by yuezk** [comment]
@rnmp I see, and I found that it's a bug of this plugin, I have fixed it in the latest commit. You can update this plugin and have a try.

**Comment by rnmp** [comment]
Confirmed fixed! Thanks for looking into it.
