### ISSUE TITLE
comma in string breaks syntax highlighting

### ISSUE THREAD

**Issue by erfanio** [MaxMEllon/vim-jsx-pretty#12]
JSX attribute value that is string doesn't get highlighted correctly if there is a comma inside.

![image](https://cloud.githubusercontent.com/assets/9994172/22449912/27f472d0-e7b7-11e6-9006-35dd6ee82680.png)

**Comment by MaxMEllon** [comment]
thanks report.

**Comment by MaxMEllon** [comment]
Fixed

![2017-01-31 11 52 16](https://cloud.githubusercontent.com/assets/9594376/22450740/05b776dc-e7ac-11e6-81e8-c6033d1a3a45.png)

**Comment by erfanio** [comment]
Thanks for the quick fix
