### ISSUE TITLE
Issue when opening new lines

### ISSUE THREAD

**Issue by rnmp** [MaxMEllon/vim-jsx-pretty#120]
Hey @yuezk! Got a new one for you :)

![pressing o](https://user-images.githubusercontent.com/22627/71260260-6b972700-2308-11ea-9557-571ba1f92252.gif)

When I open new lines on component opening tags that are multiline, I get this extra `>` character. I disabled closetags and other similar plugins and I still see this behavior. Any idea what it could be?

**Comment by yuezk** [comment]
@rnmp Comment out [this line](https://github.com/rnmp/dotfiles/blob/068fb16b507a8c87e7e313bb4a8ac7f8804910ce/.config/nvim/init.vim#L177), it's no longer needed, vim has set the filetype for `ts/tsx`, then everything will back to normal.


If you keep this line, it will cause the yats.vim to add the extra `>` character.

**Comment by rnmp** [comment]
You're a rockstar! Thanks @yuezk.
