### ISSUE TITLE
Disabling on typescript.tsx does not work

### ISSUE THREAD

**Issue by pappasam** [MaxMEllon/vim-jsx-pretty#124]
For me, the option to disable on typescript files has no effect. vim-jsx-pretty still overrides my syntax regions (I'm trying to use https://github.com/peitalin/vim-jsx-typescript/issues/4, which has better support for tsx).

```vim
let g:vim_jsx_pretty_disable_tsx = 1
```

Relevant filetype: `typescript.tsx`

**Comment by yuezk** [comment]
Hi @pappasam, it seems not an issue of this plugin, I did add the option to stop loading the syntax highlighting for tsx in this plugin.

https://github.com/MaxMEllon/vim-jsx-pretty/blob/838cfce82df8cf99df5e3a200ad23f6c0f027550/after/syntax/tsx.vim#L10-L12

Are you using the latest version?

**Comment by pappasam** [comment]
@yuezk point well taken. After doing some profiling, it turns out that [vim-styled-components](https://github.com/styled-components/vim-styled-components) was the culprit. It automatically loaded the javascript.vim for all typescript plugins. I'll file an issue there.
