### ISSUE TITLE
what command can I use to format my file ?

### ISSUE THREAD

**Issue by Abdullah-F** [MaxMEllon/vim-jsx-pretty#126]
as you posted [this](https://raw.githubusercontent.com/MaxMEllon/demos/master/vim-jsx-pretty/auto-indent.gif) in your read-me file I can see you have the sample file (sample.js) which you messed the indentation of it then entered the Visual Block mode and selected the whole file then typed a command which fixed the styling.

What is that command ? I can not figure it out.

the second question how I can make the indent automatic. I tried to open unformatted jsx file in vim after adding the plugin but nothing is changed in the file and It did not get formatted.

however the coloring of the closing tags does work fine and the other configs.

**Comment by yuezk** [comment]
1. Try the command `ggVG=` to format the whole source file.
2. This plugin can automatically indent the new line when you start a new line or press `==`. For the pre-existed unformatted file, you might need the command above to format them. It's not a code formatting tool, so if you want the more advanced formatting, you might need the other code formatting tools, like [prettier](https://prettier.io/)

**Comment by Abdullah-F** [comment]
That was clear.

Thank you, I have already yesterday started to read prettier Repo read-me file and will add it now.
thank you very much.
