### ISSUE TITLE
Not initializing correctly for typescriptreact

### ISSUE THREAD

**Issue by jonsmithers** [MaxMEllon/vim-jsx-pretty#128]
Thanks for adding such awesome support for JSX in vim!

I've noticed that the indentation doesn't always work in typescript files for me. I can reproduce with a minimal vimrc:

```vim
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'MaxMEllon/vim-jsx-pretty'
call plug#end()
```

If I open a `.tsx` file using this minimal vimrc, then any line I auto-indent is given 0 indent. If I open a buffer with filetype `javascriptreact`, the issue goes away. Here's a gif of me reproducing it on my machine:

![output](https://user-images.githubusercontent.com/2660313/78945680-e2f6ef00-7a8e-11ea-9343-9ea2b2798805.gif)

My vim version is 8.2.500.

**Comment by yuezk** [comment]
@jonsmithers Should be fixed now.

**Comment by jonsmithers** [comment]
Thanks!!
