### ISSUE TITLE
Indention issues in mocha it/describe blocks

### ISSUE THREAD

**Issue by megalithic** [MaxMEllon/vim-jsx-pretty#13]
Great plugin! Only issues I'm having is broken indention when in mocha `it` and `describe` blocks. with `vim-jsx` enabled, the automatic respect for indentions work, but of course the jsx syntax highlighting fails. with `vim-jsx-pretty` enabled, the automatic indentions fail for the scenarios fail, however, syntax highlighting of jsx is great!.

Please let me know if there are other details you need. Thanks again!

**Comment by MaxMEllon** [comment]
Thanks reports. It's an honour.

`vim-jsx-pretty` doesn't estimate,  running with `vim-jsx`. 
So, please uninstall `vim-jsx`.

I cant reproduction problem only this report.
You should report your environment in vim.

Please execute next command.

```vim
:echo substitute(&runtimepath, ',', '\n', 'g')
```

**Comment by yuezk** [comment]
I will close it as it's no longer active.
