### ISSUE TITLE
[Question] Using Emmet with vim-jsx-pretty

### ISSUE THREAD

**Issue by overbyte** [MaxMEllon/vim-jsx-pretty#131]
I had a dig through the source code but there's no obvious way i can see of doing this so I hope you guys know.

When i used mxw/vim-jsx (deprecated in favour of vim-jsx-pretty), emmet would know to use jsx-specific attribute names like `className` instead of `class`. Is there a way to fix this here please?

Thanks
;oB

**Comment by yuezk** [comment]
@overbyte Below are the emmet settings of myself. It works well for me, you can have a try.

```viml
" -----------------------------------------------------------------------------
" emmet-vim
" -----------------------------------------------------------------------------
let g:user_emmet_mode='a'    "enable all function in all mode.
let g:user_emmet_install_global = 0

let g:user_emmet_settings = {
      \  'javascript' : {
      \      'extends' : 'jsx',
      \  },
      \}

augroup emmet
  autocmd!
  autocmd FileType html,vue,css,less,jsx,javascript EmmetInstall
augroup END
```

**Comment by overbyte** [comment]
sweet dude - i'll try that and see what happens
