### ISSUE TITLE
typescript: misaligned indentation when using function shorthand with generic

### ISSUE THREAD

**Issue by zanona** [MaxMEllon/vim-jsx-pretty#132]
Whenever having the following on typescript:

```ts
const foo = <T extends string>(key:T) => {};
useEffect(doAction, []);
...
```

The indented result becomes like:
```ts
const foo = <T extends string>(key:T) => {};
   useEffect(doAction, []);
   ....
```

This is due to `foo` accepting a generic `<T extends string>`, as if we take out the generic, the indentation works as expected.

The only workaround at the moment is declaring a long form function as:

```ts
const link = function<T extends string>(key:T) {};
useEffect(doAction, []);
...
```

I've noticed that this doesn't happen on _yats.vim_, but whenever having both _yats.vim_ and _vim-jsx-pretty_, I believe that this plugin overrides the indentation rules set by yats.vim.

**Comment by yuezk** [comment]
It's hard to differentiate the JSX syntax from generic syntax in typescript with plain regex syntax highlighting because the following is also a valid JSX syntax.

```jsx
const T = 'div';

return <T extends string></T>;
```

Currently, we will treat all the `<T` as a generic and this problem can be resolved.

BTW, even though I comment out vim-jsx-pretty, this problem still exists on my machine.

**Comment by yuezk** [comment]
@zanona Update the plugin and try again.

**Comment by zanona** [comment]
@yuezk That works perfectly now. Thanks so much for adjusting this so quickly.

**Comment by malectro** [comment]
sorry for the necromancy, but i'm curious if allowing generics with names other than `T` is an impossible problem to solve or if the TS/Flow highlighting should run after the jsx highlighting? currently `vim-polyglot` runs `vim-javascript` before `jsx_pretty`.
