### ISSUE TITLE
typescript: misaligned indentation for `=` in template literal  

### ISSUE THREAD

**Issue by zanona** [MaxMEllon/vim-jsx-pretty#134]
Whenever having a string containing `=` but inside a template literal, the indentation will be increased by one level.
This doesn't seem to happen on .js files. Please see below:

```ts
const a = {
    foo: '=',
    bar: true
};

const b = {
    foo: `=`,
	bar:true
};

const c = {
    foo: 'another=word',
    bar: true
};

const d = {
    foo: `another=word`,
	bar: true
};

```

**Comment by yuezk** [comment]
@zanona It can be reproduced without the vim-jsx-pretty plugin, so it might be an issue of yats.vim

**Comment by zanona** [comment]
Thanks for checking it out, @yuezk.
Shall we consider yats.vim as a dependency for vim-jsx-pretty?

I got the impression it was a recommendation only for syntax highlighting.
Anyway, it's good to know for future issues, so I can report over there.
Thanks again.

**Comment by yuezk** [comment]
Yes. `yats.vim` is the most used dependency for `vim-jsx-pretty` as the description in README.

**Comment by yuezk** [comment]
Closing in favor of https://github.com/HerringtonDarkholme/yats.vim/issues/194
