### ISSUE TITLE
Not matching JSX with dot separator

### ISSUE THREAD

**Issue by andrewplummer** [MaxMEllon/vim-jsx-pretty#135]
Cross posted from [here](https://github.com/andymass/vim-matchup/issues/103)

With the following JSX:

```
<Layout>
  <Layout.Group horizontal center spread>
  </Layout.Group>
</Layout>
```

The `%` key will not jump to (or highlight) the closing tag for `<Layout>`.
I'm using this with the `maxmellon/vim-jsx-pretty`, unsure which is responsible for the issue.

Platform: OSX 10.15.6
Version: MacVim 8.2.539

**Comment by andymass** [comment]
What about something like this?

    <\@<=\([^/][^ \t>]*\)\g{hlend}\%(>\|$\|[ \t][^>]*\%(>\|$\)\):<\@<=/\1>

Rather than, https://github.com/MaxMEllon/vim-jsx-pretty/blob/c665d5ca4247b696f478f91b7c97b9e44442e4b6/after/ftplugin/javascript.vim#L20
