### ISSUE TITLE
Code highlighting incorrectly, when it is below jsx code with no `,` or `;` after.

### ISSUE THREAD

**Issue by yuezk** [MaxMEllon/vim-jsx-pretty#14]
It's hard to describe. 

Here is the code and snapshot.

```js
class App extends Component {
    render() {
        const arr = [
            <div></div>
        ];

        // Codes highlight incorrectly
        var foo = 'foo';
        if (foo === 'foo') {
            console.log('hello');
        }
    }
}
```

And the snapshot is

![image](https://cloud.githubusercontent.com/assets/3297602/22917815/f3f5cdec-f2c1-11e6-9ecb-460c58d8dd29.png)

But it happens only when there is not `,` or `;` after jsx code. And the following works well

```js
class App extends Component {
    render() {
        const arr = [
            <div></div>,
        ];

        // Codes highlights well
        var foo = 'foo';
        if (foo === 'foo') {
            console.log('hello');
        }
    }
}
```

![image](https://cloud.githubusercontent.com/assets/3297602/22917789/d58ef554-f2c1-11e6-8384-1b929bb2b580.png)

**Comment by yuezk** [comment]
The follow code has the same issue.

```js
class App extends Component {
    render() {
        // NOTCE: no `;` after.
        const arr = <div></div>

        // Codes highlight well
        var foo = 'foo';
        if (foo === 'foo') {
            console.log('hello');
        }
    }
}
```

**Comment by MaxMEllon** [comment]
This issue is difficult for me. So, please last a moment. 

I may possibly, I can't fix this problem.

To rewrite as below, This issue is fixed.

```diff
diff --git a/after/syntax/javascript.vim b/after/syntax/javascript.vim
index 7ec31e3..b4aee53 100644
--- a/after/syntax/javascript.vim
+++ b/after/syntax/javascript.vim
@@ -30,6 +30,7 @@ syntax region jsxRegion
       \ end=+>\n\?\s*)\@=+
       \ end=+>\n\?\s*}\@=+
       \ end=+>;\@=+
+      \ end=+>\n\@=+
       \ end=+\n\?\s\*,+
       \ end=+\s*>,\@=+
       \ end=+\s\+:\@=+
```

But, syntax-highlight break in different place.

![2017-02-15 18 25 05](https://cloud.githubusercontent.com/assets/9594376/22968014/28291f52-f3ac-11e6-8860-834ad0584bc8.png)

![2017-02-15 18 25 24](https://cloud.githubusercontent.com/assets/9594376/22968018/2c144088-f3ac-11e6-9ebc-8aa5825054d8.png)

Could you send me PR if you possible?

**Comment by yuezk** [comment]
@MaxMEllon I will try.

**Comment by MaxMEllon** [comment]
I appreciate your kindness. :smile:

I will try too.
