### ISSUE TITLE
Function declaration's closing bracket highlighted as error

### ISSUE THREAD

**Issue by andresrodco** [MaxMEllon/vim-jsx-pretty#145]
When any but the last destructuring key is surrounded by quotes, the error ocurs:
<img width="523" alt="Screen Shot 2020-12-24 at 10 40 52" src="https://user-images.githubusercontent.com/71342402/103097207-93ccfc00-45d4-11eb-9822-ede38dfaf414.png">

When any but the last destructuring key is NOT surrounded by quotes, the highlight is ok:
<img width="495" alt="Screen Shot 2020-12-24 at 10 42 31" src="https://user-images.githubusercontent.com/71342402/103097279-ca0a7b80-45d4-11eb-951c-4e2d8139069c.png">

I've managed to research a little bit the issue and this is what I found:

- This happens in a `.js` file.
- This happens to the closing bracket of a function declaration. Doesn't matter if it's exported or not.
- This happens only when inside that function there's a nested object destructuring statement AND any of the keys but the last one is surrounded by quotes, either single, double, or backticks (see images above).
- The result of SyntaxAttr for that closing bracket is `group: jsParensError->Error guifg=255(255) guibg=203(203)`, which is declared in the syntax/javascript.vim file.
- I'm using Vim Polyglot with no additional configuration for javascript files.

I'm not very savvy in regular expressions or syntax highlight debugging so I really don't know where to start looking for a fix. Hope someone can have an idea about fixing this.

**Comment by andresrodco** [comment]
Closing this bug and creating it in vim-javascript. I think I have a solution for that.

**Comment by yuezk** [comment]
@andresrodco You can use [`yuezk/vim-js`](https://github.com/yuezk/vim-js) as the alternative to `vim-javascript`. I believe it won't have this problem and I'm more familiar with that plugin.

**Comment by andresrodco** [comment]
Thanks @yuezk That plugin worked as expected!
