### ISSUE TITLE
Closing tag doesn't get colored - Gruvbox

### ISSUE THREAD

**Issue by mustafaergul** [MaxMEllon/vim-jsx-pretty#149]
Currently using gruvbox as colorscheme and in JSX file closing tags are always greyed as below. I would expect better coloring for JSX files to pretty view and same colors for closing tags.

Could you please guide me on how to fix this? I do also have the following lines that didn't help;

highlight link xmlEndTag xmlTag

let g:vim_jsx_pretty_highlight_close_tag = 1

<img width="685" alt="image" src="https://user-images.githubusercontent.com/5095547/105741845-d4a98f00-5f4b-11eb-8db5-64c232aabf79.png">

Thank you1 ❤️

**Comment by rudotriton** [comment]
It should color them by default, because I also use gruvbox. `let g:vim_jsx_pretty_highlight_close_tag=1` means that the closing tag won't be colored. If you remove that line are they still not colored?

**Comment by mustafaergul** [comment]
That worked well, not sure why I have added this :) Thanks @rudotriton !
