### ISSUE TITLE
Problem syntax

### ISSUE THREAD

**Issue by thevan96** [MaxMEllon/vim-jsx-pretty#155]
I used vim without syntax hilight, but when work project includes .jsx, feature autoindent not working.
 How to autoindent working when set syntax off?

**Comment by yuezk** [comment]
The indentation depends on the syntax group name, so disabling the syntax highlight could break the indentation.

**Comment by yuezk** [comment]
I don't know if you could enable the Vim syntax but set `g:vim_jsx_pretty_disable_js` to `1` to not highlight the JSX syntax. By doing this, the syntax groups are available, but the syntax still not highlighted.
