### ISSUE TITLE
`&nbsp;` followed by a self-closing tag breaks highlighting and indentation

### ISSUE THREAD

**Issue by vpzomtrrfrt** [MaxMEllon/vim-jsx-pretty#25]
In this example:
```
export default function Example() {
	return <div>
		&nbsp;<p />
		</div>;
}
```
The closing div is highlighted incorrectly, and is indented further than it should be.

**Comment by yuezk** [comment]
@vpzomtrrfrt @MaxMEllon This should be fixed by #35
