### ISSUE TITLE
No highlighted color on close tag

### ISSUE THREAD

**Issue by iEricKoh** [MaxMEllon/vim-jsx-pretty#28]
Check my screenshot below, the `</div>` has the white color which not the same with the start tag in green color.

![2018-08-21-19 14 38_1193_x_976](https://user-images.githubusercontent.com/8081074/44398454-773cd700-a576-11e8-8164-88ecdca08464.png)

**Comment by yuezk** [comment]
@iEricKoh I think this is because of your color scheme. You can put your cursor on the close tag, and run the fellow command in the command line to see the output.

```vim
:echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"
name") . ">"
```

**Comment by iEricKoh** [comment]
> @iEricKoh I think this is because of your color scheme. You can put your cursor on the close tag, and run the fellow command in the command line to see the output.
> 
> ```viml
> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . "> lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"
> name") . ">"
> ```

This is what I got after run your command above:
```
hi<jsxCloseString> trans<jsxCloseString> lo<>
Press ENTER or type command to continue
```

**Comment by yuezk** [comment]
@iEricKoh What's the color scheme of your vim?

**Comment by iEricKoh** [comment]
@yuezk I am using [dracula](https://github.com/dracula/vim)

**Comment by yuezk** [comment]
@iEricKoh I found the reason. We use the `Identifier` highlighting group to highlight the close tag, but the `Identifier` highlighting group in the dracula color scheme is not highlighted.

To fix this, you can add `hi! link Identifier DraculaPurple` in your vimrc, like this:

```vim
syntax on
color dracula
hi! link Identifier DraculaPurple 
```

**Comment by iEricKoh** [comment]
@yuezk Cool, it works!!!
