### ISSUE TITLE
引数にカッコを使うとハイライトが崩れる

### ISSUE THREAD

**Issue by Eiryyy** [MaxMEllon/vim-jsx-pretty#3]
カッコなしの場合
![2016-07-28 15 27 38](https://cloud.githubusercontent.com/assets/2590137/17203053/10d3e4ea-54d8-11e6-9c8d-1e475fb761e2.png)

カッコありの場合
![2016-07-28 15 28 03](https://cloud.githubusercontent.com/assets/2590137/17203057/15be6a02-54d8-11e6-9d95-a0f84bd3b39c.png)

何らかのプラグインによって解決することはできますか？あるいは修正すべき問題でしょうか？

**Comment by MaxMEllon** [comment]
報告ありがとうございます．
本プラグインの問題です．スクリーンショットまで丁寧にありがとうございます．

いまから修正に挑戦してみます．

**Comment by MaxMEllon** [comment]
![2016-07-28 16 10 12](https://cloud.githubusercontent.com/assets/9594376/17204003/d0deeb0e-54dd-11e6-8514-3e053cec1471.png)

yajs.vim が jsx を想定していないため誤マッチ jsx 内に記述された アロー関数が誤マッチしてしまっています．
これを修正するには，yajs.vim の アロー関数の ハイライトマッチ条件を変更する必要が有るかもしれません．

**Comment by MaxMEllon** [comment]
![2016-09-24 0 57 42](https://cloud.githubusercontent.com/assets/9594376/18792549/ef03ccd0-81f1-11e6-87bf-899f84aba4e5.png)

yajs.vim と vim-jsx-pretty の組み合わせでは解決ができなかったので，
vim-javascript に対応して修正いたしました．

```vim
Plug 'pangloss/vim-javascript'
Plug 'maxmellon/vim-jsx-pretty'

" optional
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'othree/es.next.syntax.vim'
```

vim-jsx-pretty を最新版にして，yajs.vim を vim-javascript にすることで解決いたいします．
あわせて，インデントの問題(#1)も改善されました．
