### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by sassanh** [MaxMEllon/vim-jsx-pretty#4]
Thanks for this plugin :-)

I guess this is indented wrong:

```
    <span
        {(text => text.length > 20
            ? text.substring(0, 19) + '...'
            : text)(subjects.join(gettext(',')))}&nbsp;
            ({Math.log2(this.props.data.key[index] * 2 || 1).toFixed().persian()} -&nbsp;
        </span>
```

last 2 lines have an extra indentation.

**Comment by MaxMEllon** [comment]
Thanks report! 
I try to make sure

**Comment by MaxMEllon** [comment]
`<span`
This tag forget `>` character?

**Comment by sassanh** [comment]
Oh such a typo. Sorry for taking your time on this.
If it's alright I wanna check another issue with you:
```
const a = <div>
    {1
            ? this.props.data.answers[column * 30 + row] & (1 << option)
            : 2
    }
</div>;
```
I guess lines starting with `?` and `:` have an extra indentation here.

**Comment by sassanh** [comment]
Take a look at this one too, it may be related:
```
const a = <span>
    {1 +\
        2}
    </span>;
```
I guess `2}` has correct indentation but `</span>` doesn't look good (extra indentation.)

**Comment by sassanh** [comment]
Please let me know if I should create separate issues. Found another one:
```
const a = <button
    x={true ? 1 : 2}
y={2}>
    {gettext('School')}
    </button>;
```
wrong indentation started in line 3.

**Comment by MaxMEllon** [comment]
humm... Thank you report. I try to fix this problem.

**Comment by MaxMEllon** [comment]
Maybe, indent not only, syntax has issue. So break indent.

**Comment by MaxMEllon** [comment]
Partially fixed

![aa](https://cloud.githubusercontent.com/assets/9594376/20394095/ad4e99ae-ad21-11e6-99b4-ec5dad545e7e.gif)

**Comment by sassanh** [comment]
@MaxMEllon thanks, looking forward on this.

**Comment by MaxMEllon** [comment]
@sassanh I already pushed to the master 😄  
I fixed it with #5.

**Comment by MaxMEllon** [comment]
Fixed!

![2016-11-17 23 54 44](https://cloud.githubusercontent.com/assets/9594376/20396679/4c80f46a-ad2a-11e6-9831-f29bef3019af.png)

**Comment by sassanh** [comment]
Thanks :-)
