### ISSUE TITLE
TSX highlighting breaks with & between two generics

### ISSUE THREAD

**Issue by vpzomtrrfrt** [MaxMEllon/vim-jsx-pretty#40]
```typescript
const a: A<B> | B<A> = {};
const b = 5;
```
With this plugin and leafgarland/typescript-vim installed, the above code highlights incorrectly.  The second generic (`<A>`) is highlighted in blue, and the following text is not highlighted at all.

**Comment by yuezk** [comment]
@vpzomtrrfrt The #39 has fixed this, will be merged soon.

**Comment by MaxMEllon** [comment]
Sorry for reviewing so late

**Comment by yuezk** [comment]
@vpzomtrrfrt You can update this plugin and see if it was fixed now.
Feel free to feedback more typescript issues. Thanks.

**Comment by vpzomtrrfrt** [comment]
Yup, looks like this is fixed now
