### ISSUE TITLE
Slow behaviour for tsx files.

### ISSUE THREAD

**Issue by amunra81** [MaxMEllon/vim-jsx-pretty#44]
on typescript files (as tsx) , after a few file switchings (let's say opening 10 - 12 files), vim/nvim becomes practical unusable if you want to open other files (it will wait more then 30 seconds to open)

**Comment by yuezk** [comment]
@amunra81 Thanks for the feedback, I will have a look.

**Comment by yuezk** [comment]
@amunra81 Sorry for the inconveniences. I have found the root cause and fixed it in the PR #45. I also tested it on my local project, it works well now. You can update the plugin now and verify it.

BTW, feel free to feedback if you have any problems. Thanks.
