### ISSUE TITLE
JavaScript syntax highlighting stop working in html files when enabling this plugin

### ISSUE THREAD

**Issue by ipatch** [MaxMEllon/vim-jsx-pretty#48]
Hello, 👋 just found out about this plugin last night, and am impressed how it works out of the box with JSX with little to no configuration files.  That said, something I noticed was that after I enable this plugin Javascript syntax highlighting inside of an `.html` file no longer works.  I put together a simple `.gif` explaining what is going on with my current Neovim setup.

![vim-jsx-pretty-borks-js-syntax-in-html-edited](https://user-images.githubusercontent.com/613805/50406175-1a506800-0786-11e9-8222-60ee958985b0.gif)

In the above GIF notice how Javascript syntax highlighting works before enabling this plugin, but after enabling, Javascript highlighting in `.html` files does not work, but then works again after disabling / removing the plugin.

Please let me know if I need to link / add any more configuration files for aiding in troubleshooting this issue.  Also all of my current Vim / Neovim configuration files can be found [here](https://github.com/ipatch/dotfiles/tree/dec/dev/editors/vim)

**Comment by yuezk** [comment]
@ipatch Thanks for your feedback, I will take a look.

**Comment by yuezk** [comment]
@ipatch I used your dotfiles, but it cannot be reproduced. Can you provide the test HTML file you used?

**Comment by yuezk** [comment]
@ipatch I found the root cause and fixed it in #49. You can update the plugin and verify it now.

BTW, if you use the `vim-polyglot` plugin, you should disable the `jsx` plugin in it. By setting `let g:polyglot_disabled = ['jsx']` in your vimrc. The jsx plugin inside vim-polyglot is from `mxw/jsx`. and it will override this plugin.

**Comment by MaxMEllon** [comment]
Just merged. Thanks report and patches.
