### ISSUE TITLE
JSX commenting | FEATURE REQUEST

### ISSUE THREAD

**Issue by ipatch** [MaxMEllon/vim-jsx-pretty#51]
Hello 👋 again,

Something I was running into the other day while working with **JSX** commenting in `.js` files is maintaining Javascript comments, `//` while being able to add JSX comments in the same `.js` file.  I asked the below question on another site,

[vi.stackexchange.com > JSX comments in .js files](https://vi.stackexchange.com/questions/18372/how-to-add-javascript-and-jsx-comments-in-the-same-js-file)

And the only supplied answer of adding the below three Vim plugins

- [vim-commentary](https://github.com/tpope/vim-commentary)
- [vim-jsx](https://github.com/mxw/vim-jsx)
- [vim-context-commentstring](https://github.com/suy/vim-context-commentstring)

does indeed allow toggling of both Javascript and JSX comments in the same `.js` files.

I also put together a lengthy gif ~ 2 minutes 30 seconds kind of explaining the current behavior and desired behavior of this Vim plugin.

![vim-jsx-pretty-jsx-commenting](https://user-images.githubusercontent.com/613805/50530143-8e5d7980-0ac0-11e9-958d-9d818f8563b0.gif)

A little bit about the above gif,
- I created a bone stock user on macOS with the name of **dottie**
- login with the user
- construct a bare bones `init.vim`
- install plugins
- configure plugins with minpac
- demo how the different plugins work.

**Comment by yuezk** [comment]
It seems a cool feature. I will take a look.

**Comment by ipatch** [comment]
@yuezk 

Kevin, man your like ...awesome.

<details>

<summary>clapping 👏</summary>

<img src="https://i.imgur.com/eyPtbXQ.gif">


</details>
