### ISSUE TITLE
TSX highlighting some generic types as error

### ISSUE THREAD

**Issue by chitoku-k** [MaxMEllon/vim-jsx-pretty#59]
Possibly related to #40.

Some complicated generic types that even compile seem to be highlighted error using this plugin.

```ts
let union: Array<string & number>
let props: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>
```

![image](https://user-images.githubusercontent.com/6535425/50728921-b0b45e80-1174-11e9-9943-38fb624cce4d.png)

My environment is Neovim v0.3.2 and the vim-jsx-pretty is f40cbf353325020f1a3501ec261c918e818e87bf.

I appreciate any efforts made for this great plugin, thanks in advance!

**Comment by chitoku-k** [comment]
Very sorry, this was not because of this plugin: vim-jsx-pretty works pretty fine in this case.

**Comment by fr3fou** [comment]
How did you manage to fix this? Are you using `typescript-vim` or `vim-polygot`? I've been struggling with the same problem.

**Comment by yuezk** [comment]
@fr3fou Disable `vim-polygot` and try again.

**Comment by fr3fou** [comment]
Now I can't get syntax highlighting to appear at all / it appears but disappears after I get out of insert mode:
![image](https://user-images.githubusercontent.com/1344906/59149058-62540600-8a19-11e9-8df3-64538f522a3c.png)

**Comment by chitoku-k** [comment]
It appears that your screenshot has a conflict with https://github.com/styled-components/vim-styled-components.

**Comment by fr3fou** [comment]
hmm, disabling it seems to have fixed it, but I have yet to fix another issue - 
![image](https://user-images.githubusercontent.com/1344906/59149164-ece93500-8a1a-11e9-916b-2f08f9aaca4e.png)

I don't know what filetype I should be using for typescript and tsx, right now it's set as `typescript` but both it and `typescript.jsx` / `typescript.tsx` give me this error smh

**Comment by chitoku-k** [comment]
I don't think any problems are remaining, except that your code has some compilation errors.

**Comment by fr3fou** [comment]
But it compiles fine :/ it's not giving me that error in vscode

**Comment by chitoku-k** [comment]
It's not because of this syntax plugin but of your plugin that runs tsserver in background. Does your project have tsconfig.json?

**Comment by fr3fou** [comment]
Yep, it also has jsx enabled. This error only occurs in some files, not all.

**Comment by chitoku-k** [comment]
That's weird... I can't guess which plugin you are using, but assuming it's coc-tsserver, how about this issue: https://github.com/neoclide/coc-tsserver/issues/35?

**Comment by fr3fou** [comment]
`autocmd BufNewFile,BufRead *.tsx set filetype=typescript.tsx`
adding this may have just fixed it
