### ISSUE TITLE
bug: can't identify jsx closing tag name separately from tag name

### ISSUE THREAD

**Issue by BerkeleyTrue** [MaxMEllon/vim-jsx-pretty#60]
Hello,

It's been a while since I've updated to the latest version. I've updated recently and found some of my custom highlighting gone.

It seems that a fix to jsTagName has overwritten this feature (or was it a bug?).

In the latest it looks like jsxOpenTag|jsxCloseTag are now being overwritten by jsxPunct.

It be great if we could get a jsClosingTagName and get the other two close/open tag working again.  

It seems that this is the behavior in the gifs in the readme as well.

Here is what I had before:

![before](https://user-images.githubusercontent.com/6775919/54158316-7cc11800-4407-11e9-85e8-af7bab38de84.png)

Here is the [commit](https://github.com/MaxMEllon/vim-jsx-pretty/commit/4a93086ef845bdc989bee74bbd869f84d6e5765f) that broke (fixed?) the syntax:

![deduplicate; much improved typescript; jsxComponentName; jsxEqual](https://user-images.githubusercontent.com/6775919/54158346-8cd8f780-4407-11e9-955a-7f28d72b9c25.png)

And what it looks like now:

![master](https://user-images.githubusercontent.com/6775919/54158351-94989c00-4407-11e9-8fe1-0bf1b0c5bc8f.png)
![tmux](https://user-images.githubusercontent.com/6775919/54158580-0670e580-4408-11e9-8448-cd985dd7c204.png)

**Comment by MaxMEllon** [comment]
Thank you report.
It's a new specification of vim-jsx-pretty for Fragments syntax.
So, can't reproduce syntax highlight before is implemented to vim-jsx-pretty a Fragments syntax.

```
  |--------------|--------------------|
  | jsxPunct     | `<tag id="sample">`|
  |              | `~________________`|
  |--------------|--------------------|
  | jsxTagName   | `<tag id="sample">`|
  |              | `_~~~_____________`|
  |--------------|--------------------|
```

i will update help and document. sorry.

**Comment by yuezk** [comment]
@BerkeleyTrue I have added this feature, it's disabled by default, you can add `let g:vim_jsx_pretty_highlight_close_tag = 1` in your vimrc to enable this feature.

**Comment by BerkeleyTrue** [comment]
@yuezk woot! thanks!

**Comment by BerkeleyTrue** [comment]
@yuezk works like a charm. Thanks again for the fix.
