### ISSUE TITLE
Cursor loses horizontal position

### ISSUE THREAD

**Issue by mnbroatch** [MaxMEllon/vim-jsx-pretty#62]
Cursor loses horizontal position on short lines when plugin is active

To reproduce, open bug.jsx with the plugin active (the only plugin, installed natively, no vimrc, vim 8.1.610).

Place your cursor on the '2'.

Press j twice.

Without the plugin installed (or in a non-js file), your cursor will be on the '5'. With the plugin, it will be on the '4'

**bug.jsx**
```javascript
123

456
```

**Comment by MaxMEllon** [comment]
Thank you report 👍 

Right reproduced the problem.
Broken horizontal place of cursor when handle `ICursorMove` event in ftdetect.vim.
https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/ftplugin/javascript.vim#L18-L21

i try fix to the timing of update highlighting.

**Comment by MaxMEllon** [comment]
workaround:

```diff
-augroup jsx_comment
-  autocmd! CursorMoved <buffer>
-  autocmd CursorMoved <buffer> call jsx_pretty#comment#update_commentstring(b:original_commentstring)
-augroup end
```

But apply this, vim-jsx-pretty dont update highlighting when cursor moved.

**Comment by yuezk** [comment]
This implemented a feature which can automatically update the comment string in the JSX file (#51).

**Comment by yuezk** [comment]
@mnbroatch This issue should have been fixed now, you can verify it by yourself.

**Comment by mnbroatch** [comment]
Thanks guys!
