### ISSUE TITLE
Support andymass/vim-matchup

### ISSUE THREAD

**Issue by davidsierradz** [MaxMEllon/vim-jsx-pretty#64]
From: [andymass/vim-matchup/issues/62](https://github.com/andymass/vim-matchup/issues/62):

> The reason this doesn't work is the open `<` and close `>` are showing up as comments:
> 
> ```
> jsxOpenPunct   xxx links to jsxPunct
> jsxPunct       xxx links to jsxCloseString
> jsxCloseString xxx links to Comment
> ```
> 
> I'm not sure whether this is intentional or a bug in the syntax definitions of MaxMEllon/vim-jsx-pretty

Thanks!

**Comment by yuezk** [comment]
Thanks for your feedback, will take a look later.

**Comment by yuezk** [comment]
@davidsierradz I have added support for the matchup plugin, you can update this plugin and verify it now. Feel free to leave comments below if you have any problems.

BTW, after this update, the `JsxHotfix` in your vimrc may don't need anymore.
