### ISSUE TITLE
Long JSX blocks lose highlighting when jumping to end of file

### ISSUE THREAD

**Issue by pbondoer** [MaxMEllon/vim-jsx-pretty#66]
Hey there!

First of all, thanks for the wonderful plugin, it's really my favorite of all vim JSX syntax plugins.

For context, I'm using the latest version of this plugin in conjuction with the latest version of `pangloss/vim-javascript`.

I work on a rather large software development project, and we use JSX to control a React router. Our router file is rather large, with lots of nested routes.

Our file looks something like this:

```jsx
import * as React from 'react';

import Module from './module';
// ... a crap ton of imports

export default (args) => {
  const Decorated = compose(
    // ... some HoC components
  )(Layout);

  return (
    <Route component={Decorated}>
      // ... a lot of routes
    </Route>
  );
};
```

I lose highlighting when jumping to the end of the file. It seems to come back right as I hit the 25th line right after the return statement.

I thought it might be a syntax sync issue, but it seems that neither of these helped:
* `syntax sync fromstart`
* `syntax sync maxlines=1000`

---

Not sure if this is related to `vim-javascript` or `vim-jsx-pretty`. Happy to assist with debugging, I've looked around syntax code but couldn't find any relevant bits. Let me know if there's any more details I can provide.

**Comment by yuezk** [comment]
Thanks for your feedback, will take a look later.

**Comment by yuezk** [comment]
@pbondoer This issue cannot be reproduced from my environment. But have encountered a similar issue with another syntax plugin. The solution is to add `syntax sync fromstart` to it.

Can you add the following line into your vimrc and restart the vim to see if it can fix this issue?

`au BufEnter *.js,*.jsx syntax sync fromstart`

**Comment by yuezk** [comment]
Do you use vim or neovim?

BTW, if you are using `vim-polyglot`, please disable (by commenting it out, not by the `g:polyglot_disabled` variable) it entirely for a moment and try again.

**Comment by pbondoer** [comment]
@yuezk 

`syntax sync` autocmds on BufEnter don't seem to do much to help fix the issue unfortunately :(

I'm on neovim. I've also disabled `vim-polyglot` but no dice. Keep in mind the file itself is over 300 lines, with the return statement JSX block spanning well over 200 of those.

**Comment by yuezk** [comment]
@pbondoer I tested it with a file contains 4000 lines of JSX code (duplicated the JSX code thousands of lines), but it can not be reproduced. 

So can you test it with the minimal vimrc like below to see if it can be reproduced?

```vim
call plug#begin()
Plug 'pangloss/vim-javascript'
Plug 'MaxMEllon/vim-jsx-pretty'
call plug#end()

filetype on
filetype plugin on
filetype indent on
syntax on
```

And if it can be reproduced with it, can you provide a test file by removing the sensitive code from it?

**Comment by pbondoer** [comment]
@yuezk 

I can definitely reproduce with that minimal `.vimrc`.

Here's [a gist to reproduce](https://gist.github.com/pbondoer/78a57a66897c0724df5b6c395f1c7612) and here's what it looks like to me:

Actual | Expected
--------|--------
![](https://uplr.it/74b26.png) | ![](https://uplr.it/f0482.png)

I've narrowed it down to line 113:

```jsx
<Redirect from="foobar/*" to="foobar" />
```

If I change `from="foobar/*"` to `from="foobar"`, it seems to work as expected. I think the `*` is what it's causing it to trip up... perhaps it is misdetecting as `import * from './foo'` syntax?

It also seems that the issue goes away as soon as you see that line. So if you remove all imports, you will see no issue with that file. But if you have the imports, jump to the end of the file with `G` and then scroll back up, you will have no highlighting until you reach that specific line.

**Comment by yuezk** [comment]
@pbondoer Thanks for your test objects.

The reason is that the `jsComment` syntax group from vim-javascript has an `extend` keyword ([here](https://github.com/pangloss/vim-javascript/blob/ee445807a71ee6933cd6cbcd74940bc288815793/syntax/javascript.vim#L204)), which means it will extend the syntax region, so the syntax is highlighted as Comment in your left image.

There is a workaround for this issue: adding `let g:javascript_plugin_jsdoc = 1` in your vimrc. This option is from [vim-javascript](https://github.com/pangloss/vim-javascript#configuration-variables). 

When jsdoc enabled, the `jsComment` syntax group is overwritten ([here](https://github.com/pangloss/vim-javascript/blob/ee445807a71ee6933cd6cbcd74940bc288815793/extras/jsdoc.vim#L2)) and the `extend` keyword is removed.

BTW, I have always enabled the jsdoc feature in my vimrc and no other issues introduced. You can have a try. I will try to find out that whether this issue can be fixed from our side.

**Comment by pbondoer** [comment]
@yuezk 

That does indeed fix the issue for me. Thanks for investigating! Weird issue though!

Feel free to close if you feel the workaround doesn't warrant a fix on your end.
