### ISSUE TITLE
Poor indentation for JSX when pressing Enter

### ISSUE THREAD

**Issue by sheerun** [MaxMEllon/vim-jsx-pretty#68]
Here's how to reproduce:

```jsx
import React from 'react';

class Foobar extends React.Component {
  render() {
    return <div></div>
  }
}
```

If you place cursor inside `<div></div>` and press enter, the result is:

```jsx
import React from 'react';

class Foobar extends React.Component {
  render() {
    return <div>
      </div>
  }
}
```

Better result would be:

```jsx
import React from 'react';

class Foobar extends React.Component {
  render() {
    return <div>
    </div>
  }
}
```

This would be analogous to how `.html` files work in vim, or when you press enter inside any parens of `function () {}`. Here's screencast to show that:

https://asciinema.org/a/qQaiDpXwRLrcFf95ViHULRpmq

**Comment by yuezk** [comment]
@sheerun Thanks for your feedback, will take a look later.

**Comment by yuezk** [comment]
@sheerun You can verify this issue with the latest commit now. Feel free to leave a comment if you still have any questions.

**Comment by sheerun** [comment]
wow, it's perfect now, thank you :)
