### ISSUE TITLE
Crash when opening large file

### ISSUE THREAD

**Issue by elgunhuseynli** [MaxMEllon/vim-jsx-pretty#72]
I tried to open minified and bundled .js file, but it is crashed. File size is 2.4MB.
Here is the error

![image](https://user-images.githubusercontent.com/49293712/59341042-2b7f3800-8d18-11e9-86b4-a411a0d13720.png)

**Comment by yuezk** [comment]
@elgunhuseynli Can you provide the bundled.js for reproducing? Thanks.

**Comment by elgunhuseynli** [comment]
@yuezk And here is the zip file.
[jsbundle.zip](https://github.com/MaxMEllon/vim-jsx-pretty/files/3283381/jsbundle.zip)

**Comment by yuezk** [comment]
@elgunhuseynli Thanks for the test objects, but I couldn't reproduce this issue with the jsbundle you provided. Does this issue happen on the source code?

**Comment by elgunhuseynli** [comment]
@yuezk Thanks for testing. No this issue doesn't happen on source.

I can still reproduce the issue. I deleted .vimrc file and all other plugins except vim-jsx-pretty and error still occur.

I thought maybe this issue occur on my Windows 10, so I tried to reproduce on linux environment and yeap it doesn't give error on linux. Also, are you using linux?

**Comment by yuezk** [comment]
@elgunhuseynli  I'm using macOS and it works well. It's a bit of hard for me to debug it with the bundled js on Windows 10. Since it works well with the source code, I am no longer spend time on this.

Thanks for your feedback again, and if it happens on the source code later, feel free to let me know.
