### ISSUE TITLE
jsxCloseString does not work with Gruvbox

### ISSUE THREAD

**Issue by escorponox** [MaxMEllon/vim-jsx-pretty#74]
jsxCloseString doesn't work well with Gruvbox, it's strange because if I do `hi link jsxCloseString GruvboxRed` in the buffer works as expected.

Something similar to https://github.com/MaxMEllon/vim-jsx-pretty/issues/28

Anyways I made a fork with the things I need.

**Comment by yuezk** [comment]
@escorponox I have been using the Gruvbox theme all the time, and the `jsxCloseString` works well for me.

![image](https://user-images.githubusercontent.com/3297602/59741126-a4443e00-929c-11e9-92ed-6ec44fe989ab.png)

Can you post your screenshot? Thanks.

**Comment by yuezk** [comment]
This issue should have been fixed in the latest version.
