### ISSUE TITLE
Syntax breaks in string literal expression

### ISSUE THREAD

**Issue by babangsund** [MaxMEllon/vim-jsx-pretty#77]
Whenever the code wraps, and a parameter has a default value which contains a literal string expression, the syntax highlighting breaks in the remaining of the file.

I've tried installing `vim-jsx-pretty` separately from `vim-polyglot`, however this did not resolve the issue.

Screenshot:
<img width="502" alt="Screenshot 2019-07-17 at 20 53 58" src="https://user-images.githubusercontent.com/52657398/61403338-6ce5a300-a8d5-11e9-8b04-529025b4b3d2.png">

If I undo the wrapping, highlighting works as intended:
<img width="1026" alt="Screenshot 2019-07-17 at 21 00 04" src="https://user-images.githubusercontent.com/52657398/61403610-f6957080-a8d5-11e9-9bd7-302db8f30feb.png">

A maximum column is common in prettier though, so this isn't really a solution. :^)

**Comment by jameswritescode** [comment]
I've been running into this issue too (heavy use of graphql-tag and styled-components reveals this _a lot_) but I was not sure if it was vim-jsx-pretty or another plugin 😬

**Comment by babangsund** [comment]
@jameswritescode Hnng 😅 
If I remove the closing `}` tag, right before the ending `, then highlighting actually works again. 🤔

**Comment by yuezk** [comment]
@babangsund @jameswritescode Can you paste your demo code? I will take an investigation.

**Comment by babangsund** [comment]
I'll toss you something tomorrow 👍

**Comment by yuezk** [comment]
@babangsund I can reproduce this issue with your code, and if I disable the vim-jsx-pretty plugin, it still exists. So it should be an issue of vim-javascript.

**Comment by yuezk** [comment]
I have submitted an issue for vim-javascript (https://github.com/pangloss/vim-javascript/issues/1177).

You can use `yajs.vim` as a workaround before this issue is fixed.

**Comment by babangsund** [comment]
Fair point. Cheers. 👍

**Comment by babangsund** [comment]
> @jameswritescode Can you provide your test code with graphql or styled-components? Maybe I can help to investigate the root cause.

I personally haven't been able to recreate the issue with styled-components or graphql - I'll let you know if anything changes :-)

**Comment by jameswritescode** [comment]
Hey! Sorry, will put something together soon! :)

**Comment by babangsund** [comment]
> Hey! Sorry, will put something together soon! :)

![you_better](https://user-images.githubusercontent.com/52657398/61553670-333ea480-aa5b-11e9-984d-176d9dfe5522.gif)

**Comment by jameswritescode** [comment]
@babangsund after digging into the issue I discovered that vim-matchup is the culprit for my highlighting problems 😅

**Comment by yuezk** [comment]
@babangsund I think there should be a `functionCall` before the opening paren of your demo code. So added it.

**Comment by babangsund** [comment]
@yuezk Have you had any experience with this issue?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52657398/61871281-b9863b00-aee0-11e9-8c54-dea3cc2e8315.gif)

**Comment by yuezk** [comment]
No, I'm not using graphql, it seems a problem with graphql, but I'll take an investigation when I have time.

**Comment by yuezk** [comment]
@babangsund Sorry for the late update.

As my [comments above](https://github.com/MaxMEllon/vim-jsx-pretty/issues/77#issuecomment-512881655), this is a [bug](https://github.com/pangloss/vim-javascript/issues/1177) from the pangloss/vim-javascript plugin. This issue could be fixed and I tried to [submit a PR](https://github.com/pangloss/vim-javascript/pull/1178) to fix it, but I found that it's not easy based on its codebase, lots of syntax groups need to be refactored.

So I started to write a new plugin to highlight JavaScript and flow.js. And now it's ready to use. You can install it and then verify this issue.

```vim
Plug 'yuezk/vim-js'
```

Note: you need update `vim-jsx-pretty` as well.

For the graphql highlight issue, if it still reproducible after installed my vim-js plugin, would you please provide the issue code for me? Thanks.

**Comment by babangsund** [comment]
It seems you've fixed the issue. Thanks!
