### ISSUE TITLE
indent decreased when given expression to attribute.

### ISSUE THREAD

**Issue by pandanoir** [MaxMEllon/vim-jsx-pretty#79]
(Sorry for my poor English...)

I found a strange indentation behavior. When JSX element is multiple line and first line includes expression, then vim-jsx-pretty decreases indentation.

```jsx
import React from 'react';

const Foobar = () => {
    return <div>
        {(() => {
            const foo="foo";
        return <input className={"foo"}
        value="bar"/>; // indent decreased!
        })()}
    </div>;
};
```

However, following code has the expected indentation.

```jsx
import React from 'react';

const Foobar = () => {
    return <div>
        {(() => {
            return <input className="foo"
                value="bar"/>;
        })()}
    </div>;
};
```

and next one also has correct indentation.

```jsx
import React from 'react';

const Foobar = () => {
    return <div>
        {(() => {
            return <input className="foo"
                value={"bar"}/>;
        })()}
    </div>;
};
```

Just a first example has broken indentation. Please fix this problem.

**Comment by yuezk** [comment]
@pandanoir This issue should be fixed in the latest commit. You can update this plugin and try it by yourself.
