### ISSUE TITLE
Less than sign bug when no space after it

### ISSUE THREAD

**Issue by Arch-Mage** [MaxMEllon/vim-jsx-pretty#8]
With this:

```javascript
// no space after '<'
0 <num
```

If you check what is current syntax on `num`, you got `jsxTagName`.

I think [this is](https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/syntax/javascript.vim#L27) the culprit.

**Comment by MaxMEllon** [comment]
Thank you report. 
I will check it. 😄

**Comment by MaxMEllon** [comment]
@Arch-Mage Fixed this problem. 

![2017-01-13 14 46 27](https://cloud.githubusercontent.com/assets/9594376/21919645/44ae4570-d99f-11e6-9046-67591d87af8a.png)
