### ISSUE TITLE
Fragment Closing Tags Different

### ISSUE THREAD

**Issue by redreceipt** [MaxMEllon/vim-jsx-pretty#81]
Seeing some inconsistencies when using JSX fragments.

<img width="714" alt="Screen Shot 2019-08-13 at 1 58 57 PM" src="https://user-images.githubusercontent.com/2659478/62965252-9f9a9280-bdd2-11e9-85c0-37ab4956d2de.png">

**Comment by yuezk** [comment]
@redreceipt It seems not very long file, could you please provide the demo code which can reproduce this issue? I would like to investigate the root cause. Thanks.

**Comment by redreceipt** [comment]
Seems to have fixed itself. If I find something reproducible, I'll open it back up.
