### ISSUE TITLE
Support javascriptreact / typescriptreact filetypes

### ISSUE THREAD

**Issue by impulse** [MaxMEllon/vim-jsx-pretty#82]
It would be nice to also have this plugin enabled if above filetypes are set.

**Comment by yuezk** [comment]
Wondering which plugin will set the filetypes to javascriptreact / typescriptreact?

**Comment by impulse** [comment]
@yuezk plugins that implement Microsoft language protocol [LSP specification](https://microsoft.github.io/language-server-protocol/specification). coc.nvim has a fallback if someone uses `javascript.jsx` or `typescript.tsx` though

**Comment by yuezk** [comment]
This plugin has no special logic for filetypes. It works well for filetypes which are javascript/typescript, javascript.jsx/typescript.tsx.

Does the rest part of your JavaScript code highlight correctly when using javascriptreact / typescriptreact?

**Comment by impulse** [comment]
No this plugin only works when using `javascript.jsx` / `typescript.tsx` not when using `javascriptreact` / `typescriptreact` hence this issue.

**Comment by yuezk** [comment]
@impulse What I mean is which javascript highlighting plugin do you use? (i.e., are you using `pangloss/vim-javascript` or `yajs.vim` or whatever?) Do they work well for the `javascriptreact` / `typescriptreact` filetypes.

**Comment by impulse** [comment]
@yuezk I use the following:
```
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'maxmellon/vim-jsx-pretty'
```

There is no syntax highlighting for javascriptreact (javascript.jsx is the above split)

![Screenshot 2019-08-19 at 08 21 22](https://user-images.githubusercontent.com/8146736/63243282-5aef7b00-c25a-11e9-9cde-d83556cfc2b5.png)

**Comment by yuezk** [comment]
Do you know which plugin changed the filetype to `javascriptreact`?

**Comment by impulse** [comment]
@yuezk from what I know they are no official vim filetypes so I set them manually 
(I have no plugin who does this)
```
autocmd bufnewfile,bufread *.jsx set filetype=javascript.jsx
autocmd bufnewfile,bufread *.tsx set filetype=typescript.tsx
```

Someone might however set the filetype for `javascriptreact` or `typescriptreact` instead and have no syntax highlighting. I thought it would just be a nice addition for that case.

**Comment by yuezk** [comment]
Currently, I have no idea how to implement this.

**Comment by impulse** [comment]
**Update**: I opened up an issue over at the vim repo and talked with the author. He did not like making the dot syntax official, however he accepted the proposal on making `javascriptreact` and `typescriptreact`official vim filetypes. 

Unfortunately this would be my only affected plugin by that change. I'll take a look at the source if I can come up with a solution.

Discussion for reference: https://github.com/vim/vim/issues/4830

**Comment by yuezk** [comment]
@impulse Appreciate for your follow up.

But for React users who use `.js` as the extension, the filetype is still `javascript`, right? If it is that case, I want to know if the `coc.vim` plugin works as expected?

**Comment by impulse** [comment]
> @impulse Appreciate for your follow up.
> 
> But for React users who use `.js` as the extension, the filetype is still `javascript`, right? If it is that case, I want to know if the `coc.vim` plugin works as expected?

Yeah .js will continue to be filetype `javascript`. The coc.vim plugin works as it would in VSCode since language servers triggers on [both](https://github.com/mhartington/nvim-typescript/blob/baeae12457de151b99cb953fdb6a6bf04ee454ac/plugin/nvim_typescript.vim#L125) extensions. Extensions and snippets usually define which filetypes are supported in their `package.json`.

**Comment by impulse** [comment]
Not sure if you guys changed something in the meanwhile but the issue is resolved for me.

**Comment by yuezk** [comment]
Actually, we didn't change anything about this issue. 😅

**Comment by Trial-In-Error** [comment]
Just ran into this myself. Pretty sure the offending plugin is [coctsserver](https://github.com/neoclide/coc-tsserver/blob/master/Readme.md#coc-tsserver). I added the two autocmd's that @impulse mentioned and appear to have both tsserver fixes and vim-jsx-pretty highlighting and indentation. Whoo!

**Comment by yuezk** [comment]
@Trial-In-Error Thanks for your feedback, glad it works well. BTW, I'm wondering about the version of your Vim.

**Comment by Trial-In-Error** [comment]
nvim @ v0.4.2
```
$ vim --version
NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190916-19272-18joql2/neovim-0.4.2/build/config -I/tmp/neovim-20190916-19272-18joql2/neovim-0.4.2/src -I/usr/local/include -I/tmp/neovim-20190916-19272-18joql2/neovim-0.4.2/deps-build/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20190916-19272-18joql2/neovim-0.4.2/build/src/nvim/auto -I/tmp/neovim-20190916-19272-18joql2/neovim-0.4.2/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.2/share/nvim"

Run :checkhealth for more info
```

**Comment by impulse** [comment]
@Trial-In-Error I am actually not using those autocmds anymore on the same nvim version. It works fine for the javascriptreact and typescriptreact filetypes for me.

My dotfiles for reference: https://github.com/impulse/dotfiles/blob/master/vim/.vimrc
