### ISSUE TITLE
The cursor movement lags after the new way of restoring the cursor

### ISSUE THREAD

**Issue by APZelos** [MaxMEllon/vim-jsx-pretty#88]
After the last commit https://github.com/MaxMEllon/vim-jsx-pretty/commit/6871eb1696478a8e295bab3e5ae7aae05faa2605 the cursor movement lags.

To reproduce keep `h`/`j`/`k`/`l` pressed with high key repeat.

OS: macOS (10.14.6)
terminal: Kitty / iTerm2
editor: neovim (0.4.2)

**Comment by yuezk** [comment]
@APZelos Thanks for your feedback, PR has been reverted.
