### ISSUE TITLE
Not get highlighted when tagname is not directly followed by '>'

### ISSUE THREAD

**Issue by Arch-Mage** [MaxMEllon/vim-jsx-pretty#9]
After issue #8, there's opening jsx tag only highlighted if directly followed by closing angle bracket. So, with this:

```javascript
function App() {
    return (
        <div className="App">
            <div></div>
        </div>
    )
}
```

Line number 3 doesn't got highlighted by jsx. I think the culprit still [this start pattern](https://github.com/MaxMEllon/vim-jsx-pretty/blob/master/after/syntax/javascript.vim#L27).

**Comment by MaxMEllon** [comment]
sorry, I reverted source code, so this issue is ceased, and reopen #8
