### ISSUE TITLE
Indent is wrong when line ends with a braced expression

### ISSUE THREAD

**Issue by b-nik** [MaxMEllon/vim-jsx-pretty#91]
Hello, I'm using this plugin through vim-polyglot on Vim 8.1-1967

When a {} expression is at the end or at the beginning of a line in a render function, then
the indent breaks. Below is the exact indent that is produced:

```jsx
function foo() {
  return (
    <>
      <div>
        Some test {this.props.value.id} and
        some good text to top it
      </div>

      <div>
Some test {this.props.value.id}
some good text to top it
    </div>

    <div>
      Some test and some more
        {this.props.value.id} some good text to top it
      </div>
    </>
  )
}
```

**Comment by moll** [comment]
It seems to also affect the following nested use:

```jsx
<ul id="all-subscriptions">
	{subscriptions.map((subscription) => <li>
		<h3>{subscription.initiative_uuid}</h3>
	</li>)}
</ul>
```

It doesn't detect the nesting of `<li>` and insists `<h3>` should align with `{subscriptions...`.

**Comment by moll** [comment]
In fact, if the above snippet is part of another tag, it also seems to break the nesting of `</ul>`. It tries to unnest `</ul>` and move it one level lower (leftward) than its opening tag `<ul>`.

**Comment by yuezk** [comment]
Thanks for the feedback, I will take a look when I have the time.

**Comment by yuezk** [comment]
@b-nik @moll Sorry for the late update. I have made lots of changes for this plugin, seems that this issue has been fixed in these changes. So could you please update the plugin and verify it? Thanks.

**Comment by b-nik** [comment]
@yuezk Tested and it works now. Thanks for your work :)
