### ISSUE TITLE
Is this plugin support js files ?

### ISSUE THREAD

**Issue by kyoz** [MaxMEllon/vim-jsx-pretty#92]
Firstly, thank you for awesome plugin. Currently i'm learning React so i want to implement this to match my [purify](https://github.com/kyoz/purify)'s color.

Of course i know this plugin aiming for jsx, but in the indent example i see that you are using js file. I'v tried js file but it not working. Am i missing anything.

By the way, i'm trying to support this plugin for my vim theme so i tried this:

```
call s:hi('jsxTagName',      { 'fg': s:pink })
call s:hi('jsxOpenPunct',    { 'fg': s:blue })
call s:hi('jsxClosePunct',   { 'fg': s:blue })
call s:hi('jsxCloseString',  { 'fg': s:blue })

" TODO: Add more jsx syntax for react
function! s:add_more_jsx_syntax()
     syn keyword cDeclarationOverwrite var const type 
     syn match jsxBraces       "[{}\[\]]"
     syn match jsxParens       "[()]"
     syn match jsxOpSymbols    "=\{1,2}\|!=\|<\|>\|>=\|<=\|++\|+=\|--\|-="
     syn match jsxEndColons    "[,]"
     syn match jsxLogicSymbols "\(&&\)\|\(||\)\|\(!\)"

     call s:hi('jsxDeclarationOverwrite', { 'fg': s:green, 'styles': [s:styles.italic] })
     call s:hi('jsxBraces',               { 'fg': s:blue })
     call s:hi('jsxParens',               { 'fg': s:pink })
     call s:hi('jsxOpSymbols',            { 'fg': s:pink })
     call s:hi('jsxEndColons',            { 'fg': s:pink })
     call s:hi('jsxLogicSymbols',         { 'fg': s:blue })
endfunction

augroup purify_jsx
    autocmd!
    autocmd Filetype javascriptreact call s:add_more_jsx_syntax() 
augroup END
```

But it's seem with `autocmd Filetype javascriptreact call s:add_more_jsx_syntax() `. It overwrite your plugins. Is there a way i can handle this.

Thank you in advance :heart:

**Comment by kyoz** [comment]
I forgot a picture to demonstrate this.

On the left is 'jsx' and on the right is 'js' file:

![](https://i.imgur.com/rOc1n42.png)

I'm just using [leafgarland/typescript-vim](https://github.com/leafgarland/typescript-vim) plugin for typescript. The rest is all vim built-in syntax.

**Comment by yuezk** [comment]
I think it's a problem with your plugin. The syntax groups defined in your color.vim broke the syntax highlighting.

Try to comment out this line.

https://github.com/kyoz/purify/blob/2fd85fb6a448af98abd0a8452a8849d7cd7a3bcc/vim/colors/purify.vim#L365

**Comment by kyoz** [comment]
Yeah, i'v tested. it's definitely the error of that syntax:

```viml
syn match   javascriptOpSymbols  "=\{1,3}\|!==\|!=\|<\|>\|>=\|<=\|++\|+=\|--\|-="
```

But i'v tried this regex, it's working normally. I really don't know what cause conflict error there. Do you have any idea. Sorry i'm not really good at regex.

**Comment by yuezk** [comment]
The definition order of the syntax in Vim matters. So in my humble opinion, if you want to overwrite the syntax of some file type, you would better do it in the `syntax/<filetype>.vim`.

So for this issue, you can try to move the overwrite rules to the `syntax/javascript.vim` file of your plugin.

**Comment by kyoz** [comment]
Hi @yuezk , that's really a good idea. I'v updated my plugin to separate custom defined syntax in `syntax/` folder and it now work perfectly.

![](https://i.imgur.com/pjm883f.png)

So, i'll close this issue cause this's not vim-jsx-pretty issue. Thank you a lot for your plugin and helping :heart:
