### ISSUE TITLE
How can I force jsx syntax highlighting?

### ISSUE THREAD

**Issue by alecschule** [MaxMEllon/vim-jsx-pretty#95]
Hi,

I apologize if this is a silly question, but I can't figure it out. I want to force JSX syntax highlighting in a file with something like `set syntax=jsx` (this results in no highlighting at all), but I can't get it to work. My first thought was to try other names, including `jsx-pretty`, `vim-jsx-pretty`, and `javascript.jsx`, but I had no success.

Can you please point me to the right syntax command?

**Comment by yuezk** [comment]
@alecschule  You can try this command: `set syntax=javascript`.

**Comment by alecschule** [comment]
Thank you for the reply. The JSX part of my javascript highlighting doesn't seem to work, so maybe something went wrong with the plugin install. My other plugins work fine, so I may follow up here if I can pinpoint exactly what went wrong.
