### ISSUE TITLE
jsx detection breaks highlighting js left shift

### ISSUE THREAD

**Issue by devsnek** [MaxMEllon/vim-jsx-pretty#96]
> repost from https://github.com/sheerun/vim-polyglot/issues/439

In a JS left shift expression (`a << b`), if the rhs is an identifier, it switches to jsx highlighting. It works fine if the rhs is not an identifier.

![](https://gc.gy/40447692.png)
![](https://gc.gy/40447705.png)
![](https://gc.gy/40447717.png)
![](https://gc.gy/40447740.png)

**Comment by yuezk** [comment]
Hi, @devsnek Thanks for your feedback. Please update this plugin and verify it.
